import { QueryClientProviders } from "@/app/providers/queryClient/queryClientProvider";
import AppSidebar from "@/components/commons/app-sidebar";
import Footer from "@/components/commons/footer";
import Navbar from "@/components/commons/navbar";
import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex h-screen overflow-hidden">
      <aside className="w-64 shrink-0 border-r">
        <AppSidebar />
      </aside>

      <div className="flex flex-1 flex-col">
        <header className="shrink-0 border-b">
          <Navbar />
        </header>

        <main className="flex-1 overflow-y-auto">
          {children}
          <Footer />
        </main>
      </div>
    </div>
  );
}
